In [1]:
import numpy as np

In [3]:
test_array = [10, 41, 8, 16, 20, 36, 9, 13, 20]

In [5]:
npa = np.array(test_array)

In [10]:
np.argsort(npa)

array([2, 6, 0, 7, 3, 4, 8, 5, 1], dtype=int64)

In [19]:
npa[np.argsort(npa)][-3:]

array([20, 36, 41])

In [20]:
npa[np.argsort(npa)][:3]

array([ 8,  9, 10])